### ISSUE TITLE
Stucked after reconnection

### ISSUE THREAD

**Issue by stacyharper** [4e6/mpv-reload#10]
Hello there !

After disconnecting (or toggeling wireless connection by example), the script will reload the resources but mpv will stay "paused". I have to press space two time (one to actually pause, one to unpause) to play again.

Is it a known issue ?

**Comment by stacyharper** [comment]
If I understand correct, mpv-reload should unpause the video somewhere after this ? https://paste.sr.ht/~stacyharper/162a85e917092336e8f089c4379f81c01516356a#output-L61

**Comment by 4e6** [comment]
@stacyharper thanks for the report. Don't know how I missed this issue. I'm trying to keep an eye on GitHub notifications, so feel free to ping me if I'm not responding.

As for the issue, I was able to reproduce this behavior and merged a workaround. Please check that it works for you.

**Comment by stacyharper** [comment]
No worries about missing this.
Nice it works ! Thanks a lot ! :D
