### ISSUE TITLE
The loadfile option must be an integer: start=+104.792667

### ISSUE THREAD

**Issue by mortyobnoxious** [4e6/mpv-reload#19]
Reloading doesn't work and gives this error on console.

![image](https://github.com/4e6/mpv-reload/assets/42044258/8018453c-af3d-4893-b227-d71810942afe)

**Comment by pcotaku** [comment]
I've encountered the exact same issue.
![image](https://github.com/4e6/mpv-reload/assets/143455624/c7e308b2-3237-4e1b-827f-62e7ef76e7a3)

**Comment by mesvam** [comment]
The syntax for `loadfile` changed https://github.com/mpv-player/mpv/issues/13656
