### ISSUE TITLE
Format code changes when twitch stream is ended

### ISSUE THREAD

**Issue by ghost** [4e6/mpv-reload#3]
On twitch `720p-0` in VOD of current live stream is `720p30` in VOD after stream is ended. And `720p-1` is `720p60`. 
So, if i choose to watch "live" VOD with `720p-1` quality, and stream is ended, so when i reload it, video is quitting, because there is no such format code now, it's changed to `720p60`.

**Comment by 4e6** [comment]
I checked the code. When a video is reloaded, ytdl [on_load hook](https://github.com/mpv-player/mpv/blob/0d964471b81f3b136c29f4bd659796f47fb49892/player/lua/ytdl_hook.lua#L348) just passes `--format` option you specified.

Running mpv with `--msg-level='ytdl_hook=debug'` shows default options:

```
[ytdl_hook] Running: youtube-dl --no-warnings -J --flat-playlist --sub-format ass/srt/best --no-playlist --format bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best --all-subs
```

There is nothing we can do if the provided format is not available. Youtube-dl manual has [format selection](https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection) section. The best thing you can do is to specify less strict format selection string, which will compare formats without relying on their equality.
