### ISSUE TITLE
Youtube video stuttering after reload 

### ISSUE THREAD

**Issue by Marius30** [4e6/mpv-reload#9]
Hi guys,

Thanks for the awesome workaround, I faced buffering issues for weeks.

The reload works fine, but after the reload my video stutters, it seems that my mpv.conf is not used after the reload. 
Do you have a solution how mpv uses the mpv.conf after reload or an idea why the video stutters after reload, if normally the mpv.conf is used after reload?

**Comment by 4e6** [comment]
I didn't experience this behavior myself. The script uses the [loadfile](https://mpv.io/manual/stable/#command-interface-[%3Coptions%3E]]) command to reload the source when it's stuck. From the command description, it doesn't look like it affects the application config.

Does the shuttering happen after reloading the video when it was stuck, or it also happens after reloading the video with `Ctrl+r` hotkey?

**Comment by Marius30** [comment]
Hi, 
thank you for you're response.

But I now use yt-dlp instead of youtube-dl, this solved my issue.
